// -------------------------------------------------------------
//
// Module: filterBP13
// Generated by MATLAB(R) 23.2 and Filter Design HDL Coder 23.2.
// Generated on: 2024-03-29 17:57:19
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// ResetInputPort: resetn
// Name: filterBP13
// ResetAssertedLevel: Active-low
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off
// LoopUnrolling: on

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 41
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s16,15 -> [-1 1)
// Input             : s24,23 -> [-1 1)
// Filter Internals  : Specify Precision
//   Output          : s24,23 -> [-1 1)
//   Product         : s31,30 -> [-1 1)
//   Accumulator     : s33,30 -> [-4 4)
//   Round Mode      : convergent
//   Overflow Mode   : saturate
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module filterBP13
               (
                clk,
                clk_enable,
                resetn,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   resetn; 
  input   signed [23:0] filter_in; //sfix24_En23
  output  signed [23:0] filter_out; //sfix24_En23

////////////////////////////////////////////////////////////////
//Module Architecture: filterBP13
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000000101101011; //sfix16_En15
  parameter signed [15:0] coeff2 = 16'b1111111010111010; //sfix16_En15
  parameter signed [15:0] coeff3 = 16'b1111111110111111; //sfix16_En15
  parameter signed [15:0] coeff4 = 16'b0000000011100110; //sfix16_En15
  parameter signed [15:0] coeff5 = 16'b1111110110011100; //sfix16_En15
  parameter signed [15:0] coeff6 = 16'b0000001001100010; //sfix16_En15
  parameter signed [15:0] coeff7 = 16'b1111110101000111; //sfix16_En15
  parameter signed [15:0] coeff8 = 16'b0000000101000111; //sfix16_En15
  parameter signed [15:0] coeff9 = 16'b1111111110111101; //sfix16_En15
  parameter signed [15:0] coeff10 = 16'b1111110111101000; //sfix16_En15
  parameter signed [15:0] coeff11 = 16'b0000001100111100; //sfix16_En15
  parameter signed [15:0] coeff12 = 16'b1111101100111100; //sfix16_En15
  parameter signed [15:0] coeff13 = 16'b0000010000100001; //sfix16_En15
  parameter signed [15:0] coeff14 = 16'b1111110011010100; //sfix16_En15
  parameter signed [15:0] coeff15 = 16'b1111111110111100; //sfix16_En15
  parameter signed [15:0] coeff16 = 16'b0000001111010001; //sfix16_En15
  parameter signed [15:0] coeff17 = 16'b1111011011100000; //sfix16_En15
  parameter signed [15:0] coeff18 = 16'b0000110101100010; //sfix16_En15
  parameter signed [15:0] coeff19 = 16'b1110110111111101; //sfix16_En15
  parameter signed [15:0] coeff20 = 16'b0001010000111011; //sfix16_En15
  parameter signed [15:0] coeff21 = 16'b0110101100010101; //sfix16_En15
  parameter signed [15:0] coeff22 = 16'b0001010000111011; //sfix16_En15
  parameter signed [15:0] coeff23 = 16'b1110110111111101; //sfix16_En15
  parameter signed [15:0] coeff24 = 16'b0000110101100010; //sfix16_En15
  parameter signed [15:0] coeff25 = 16'b1111011011100000; //sfix16_En15
  parameter signed [15:0] coeff26 = 16'b0000001111010001; //sfix16_En15
  parameter signed [15:0] coeff27 = 16'b1111111110111100; //sfix16_En15
  parameter signed [15:0] coeff28 = 16'b1111110011010100; //sfix16_En15
  parameter signed [15:0] coeff29 = 16'b0000010000100001; //sfix16_En15
  parameter signed [15:0] coeff30 = 16'b1111101100111100; //sfix16_En15
  parameter signed [15:0] coeff31 = 16'b0000001100111100; //sfix16_En15
  parameter signed [15:0] coeff32 = 16'b1111110111101000; //sfix16_En15
  parameter signed [15:0] coeff33 = 16'b1111111110111101; //sfix16_En15
  parameter signed [15:0] coeff34 = 16'b0000000101000111; //sfix16_En15
  parameter signed [15:0] coeff35 = 16'b1111110101000111; //sfix16_En15
  parameter signed [15:0] coeff36 = 16'b0000001001100010; //sfix16_En15
  parameter signed [15:0] coeff37 = 16'b1111110110011100; //sfix16_En15
  parameter signed [15:0] coeff38 = 16'b0000000011100110; //sfix16_En15
  parameter signed [15:0] coeff39 = 16'b1111111110111111; //sfix16_En15
  parameter signed [15:0] coeff40 = 16'b1111111010111010; //sfix16_En15
  parameter signed [15:0] coeff41 = 16'b0000000101101011; //sfix16_En15

  // Signals
  reg  signed [23:0] delay_pipeline [0:40] ; // sfix24_En23
  wire signed [30:0] product41; // sfix31_En30
  wire signed [39:0] mul_temp; // sfix40_En38
  wire signed [30:0] product40; // sfix31_En30
  wire signed [39:0] mul_temp_1; // sfix40_En38
  wire signed [30:0] product39; // sfix31_En30
  wire signed [39:0] mul_temp_2; // sfix40_En38
  wire signed [30:0] product38; // sfix31_En30
  wire signed [39:0] mul_temp_3; // sfix40_En38
  wire signed [30:0] product37; // sfix31_En30
  wire signed [39:0] mul_temp_4; // sfix40_En38
  wire signed [30:0] product36; // sfix31_En30
  wire signed [39:0] mul_temp_5; // sfix40_En38
  wire signed [30:0] product35; // sfix31_En30
  wire signed [39:0] mul_temp_6; // sfix40_En38
  wire signed [30:0] product34; // sfix31_En30
  wire signed [39:0] mul_temp_7; // sfix40_En38
  wire signed [30:0] product33; // sfix31_En30
  wire signed [39:0] mul_temp_8; // sfix40_En38
  wire signed [30:0] product32; // sfix31_En30
  wire signed [39:0] mul_temp_9; // sfix40_En38
  wire signed [30:0] product31; // sfix31_En30
  wire signed [39:0] mul_temp_10; // sfix40_En38
  wire signed [30:0] product30; // sfix31_En30
  wire signed [39:0] mul_temp_11; // sfix40_En38
  wire signed [30:0] product29; // sfix31_En30
  wire signed [39:0] mul_temp_12; // sfix40_En38
  wire signed [30:0] product28; // sfix31_En30
  wire signed [39:0] mul_temp_13; // sfix40_En38
  wire signed [30:0] product27; // sfix31_En30
  wire signed [39:0] mul_temp_14; // sfix40_En38
  wire signed [30:0] product26; // sfix31_En30
  wire signed [39:0] mul_temp_15; // sfix40_En38
  wire signed [30:0] product25; // sfix31_En30
  wire signed [39:0] mul_temp_16; // sfix40_En38
  wire signed [30:0] product24; // sfix31_En30
  wire signed [39:0] mul_temp_17; // sfix40_En38
  wire signed [30:0] product23; // sfix31_En30
  wire signed [39:0] mul_temp_18; // sfix40_En38
  wire signed [30:0] product22; // sfix31_En30
  wire signed [39:0] mul_temp_19; // sfix40_En38
  wire signed [30:0] product21; // sfix31_En30
  wire signed [39:0] mul_temp_20; // sfix40_En38
  wire signed [30:0] product20; // sfix31_En30
  wire signed [39:0] mul_temp_21; // sfix40_En38
  wire signed [30:0] product19; // sfix31_En30
  wire signed [39:0] mul_temp_22; // sfix40_En38
  wire signed [30:0] product18; // sfix31_En30
  wire signed [39:0] mul_temp_23; // sfix40_En38
  wire signed [30:0] product17; // sfix31_En30
  wire signed [39:0] mul_temp_24; // sfix40_En38
  wire signed [30:0] product16; // sfix31_En30
  wire signed [39:0] mul_temp_25; // sfix40_En38
  wire signed [30:0] product15; // sfix31_En30
  wire signed [39:0] mul_temp_26; // sfix40_En38
  wire signed [30:0] product14; // sfix31_En30
  wire signed [39:0] mul_temp_27; // sfix40_En38
  wire signed [30:0] product13; // sfix31_En30
  wire signed [39:0] mul_temp_28; // sfix40_En38
  wire signed [30:0] product12; // sfix31_En30
  wire signed [39:0] mul_temp_29; // sfix40_En38
  wire signed [30:0] product11; // sfix31_En30
  wire signed [39:0] mul_temp_30; // sfix40_En38
  wire signed [30:0] product10; // sfix31_En30
  wire signed [39:0] mul_temp_31; // sfix40_En38
  wire signed [30:0] product9; // sfix31_En30
  wire signed [39:0] mul_temp_32; // sfix40_En38
  wire signed [30:0] product8; // sfix31_En30
  wire signed [39:0] mul_temp_33; // sfix40_En38
  wire signed [30:0] product7; // sfix31_En30
  wire signed [39:0] mul_temp_34; // sfix40_En38
  wire signed [30:0] product6; // sfix31_En30
  wire signed [39:0] mul_temp_35; // sfix40_En38
  wire signed [30:0] product5; // sfix31_En30
  wire signed [39:0] mul_temp_36; // sfix40_En38
  wire signed [30:0] product4; // sfix31_En30
  wire signed [39:0] mul_temp_37; // sfix40_En38
  wire signed [30:0] product3; // sfix31_En30
  wire signed [39:0] mul_temp_38; // sfix40_En38
  wire signed [30:0] product2; // sfix31_En30
  wire signed [39:0] mul_temp_39; // sfix40_En38
  wire signed [32:0] product1_cast; // sfix33_En30
  wire signed [30:0] product1; // sfix31_En30
  wire signed [39:0] mul_temp_40; // sfix40_En38
  wire signed [32:0] sum1; // sfix33_En30
  wire signed [32:0] add_signext; // sfix33_En30
  wire signed [32:0] add_signext_1; // sfix33_En30
  wire signed [33:0] add_temp; // sfix34_En30
  wire signed [32:0] sum2; // sfix33_En30
  wire signed [32:0] add_signext_2; // sfix33_En30
  wire signed [32:0] add_signext_3; // sfix33_En30
  wire signed [33:0] add_temp_1; // sfix34_En30
  wire signed [32:0] sum3; // sfix33_En30
  wire signed [32:0] add_signext_4; // sfix33_En30
  wire signed [32:0] add_signext_5; // sfix33_En30
  wire signed [33:0] add_temp_2; // sfix34_En30
  wire signed [32:0] sum4; // sfix33_En30
  wire signed [32:0] add_signext_6; // sfix33_En30
  wire signed [32:0] add_signext_7; // sfix33_En30
  wire signed [33:0] add_temp_3; // sfix34_En30
  wire signed [32:0] sum5; // sfix33_En30
  wire signed [32:0] add_signext_8; // sfix33_En30
  wire signed [32:0] add_signext_9; // sfix33_En30
  wire signed [33:0] add_temp_4; // sfix34_En30
  wire signed [32:0] sum6; // sfix33_En30
  wire signed [32:0] add_signext_10; // sfix33_En30
  wire signed [32:0] add_signext_11; // sfix33_En30
  wire signed [33:0] add_temp_5; // sfix34_En30
  wire signed [32:0] sum7; // sfix33_En30
  wire signed [32:0] add_signext_12; // sfix33_En30
  wire signed [32:0] add_signext_13; // sfix33_En30
  wire signed [33:0] add_temp_6; // sfix34_En30
  wire signed [32:0] sum8; // sfix33_En30
  wire signed [32:0] add_signext_14; // sfix33_En30
  wire signed [32:0] add_signext_15; // sfix33_En30
  wire signed [33:0] add_temp_7; // sfix34_En30
  wire signed [32:0] sum9; // sfix33_En30
  wire signed [32:0] add_signext_16; // sfix33_En30
  wire signed [32:0] add_signext_17; // sfix33_En30
  wire signed [33:0] add_temp_8; // sfix34_En30
  wire signed [32:0] sum10; // sfix33_En30
  wire signed [32:0] add_signext_18; // sfix33_En30
  wire signed [32:0] add_signext_19; // sfix33_En30
  wire signed [33:0] add_temp_9; // sfix34_En30
  wire signed [32:0] sum11; // sfix33_En30
  wire signed [32:0] add_signext_20; // sfix33_En30
  wire signed [32:0] add_signext_21; // sfix33_En30
  wire signed [33:0] add_temp_10; // sfix34_En30
  wire signed [32:0] sum12; // sfix33_En30
  wire signed [32:0] add_signext_22; // sfix33_En30
  wire signed [32:0] add_signext_23; // sfix33_En30
  wire signed [33:0] add_temp_11; // sfix34_En30
  wire signed [32:0] sum13; // sfix33_En30
  wire signed [32:0] add_signext_24; // sfix33_En30
  wire signed [32:0] add_signext_25; // sfix33_En30
  wire signed [33:0] add_temp_12; // sfix34_En30
  wire signed [32:0] sum14; // sfix33_En30
  wire signed [32:0] add_signext_26; // sfix33_En30
  wire signed [32:0] add_signext_27; // sfix33_En30
  wire signed [33:0] add_temp_13; // sfix34_En30
  wire signed [32:0] sum15; // sfix33_En30
  wire signed [32:0] add_signext_28; // sfix33_En30
  wire signed [32:0] add_signext_29; // sfix33_En30
  wire signed [33:0] add_temp_14; // sfix34_En30
  wire signed [32:0] sum16; // sfix33_En30
  wire signed [32:0] add_signext_30; // sfix33_En30
  wire signed [32:0] add_signext_31; // sfix33_En30
  wire signed [33:0] add_temp_15; // sfix34_En30
  wire signed [32:0] sum17; // sfix33_En30
  wire signed [32:0] add_signext_32; // sfix33_En30
  wire signed [32:0] add_signext_33; // sfix33_En30
  wire signed [33:0] add_temp_16; // sfix34_En30
  wire signed [32:0] sum18; // sfix33_En30
  wire signed [32:0] add_signext_34; // sfix33_En30
  wire signed [32:0] add_signext_35; // sfix33_En30
  wire signed [33:0] add_temp_17; // sfix34_En30
  wire signed [32:0] sum19; // sfix33_En30
  wire signed [32:0] add_signext_36; // sfix33_En30
  wire signed [32:0] add_signext_37; // sfix33_En30
  wire signed [33:0] add_temp_18; // sfix34_En30
  wire signed [32:0] sum20; // sfix33_En30
  wire signed [32:0] add_signext_38; // sfix33_En30
  wire signed [32:0] add_signext_39; // sfix33_En30
  wire signed [33:0] add_temp_19; // sfix34_En30
  wire signed [32:0] sum21; // sfix33_En30
  wire signed [32:0] add_signext_40; // sfix33_En30
  wire signed [32:0] add_signext_41; // sfix33_En30
  wire signed [33:0] add_temp_20; // sfix34_En30
  wire signed [32:0] sum22; // sfix33_En30
  wire signed [32:0] add_signext_42; // sfix33_En30
  wire signed [32:0] add_signext_43; // sfix33_En30
  wire signed [33:0] add_temp_21; // sfix34_En30
  wire signed [32:0] sum23; // sfix33_En30
  wire signed [32:0] add_signext_44; // sfix33_En30
  wire signed [32:0] add_signext_45; // sfix33_En30
  wire signed [33:0] add_temp_22; // sfix34_En30
  wire signed [32:0] sum24; // sfix33_En30
  wire signed [32:0] add_signext_46; // sfix33_En30
  wire signed [32:0] add_signext_47; // sfix33_En30
  wire signed [33:0] add_temp_23; // sfix34_En30
  wire signed [32:0] sum25; // sfix33_En30
  wire signed [32:0] add_signext_48; // sfix33_En30
  wire signed [32:0] add_signext_49; // sfix33_En30
  wire signed [33:0] add_temp_24; // sfix34_En30
  wire signed [32:0] sum26; // sfix33_En30
  wire signed [32:0] add_signext_50; // sfix33_En30
  wire signed [32:0] add_signext_51; // sfix33_En30
  wire signed [33:0] add_temp_25; // sfix34_En30
  wire signed [32:0] sum27; // sfix33_En30
  wire signed [32:0] add_signext_52; // sfix33_En30
  wire signed [32:0] add_signext_53; // sfix33_En30
  wire signed [33:0] add_temp_26; // sfix34_En30
  wire signed [32:0] sum28; // sfix33_En30
  wire signed [32:0] add_signext_54; // sfix33_En30
  wire signed [32:0] add_signext_55; // sfix33_En30
  wire signed [33:0] add_temp_27; // sfix34_En30
  wire signed [32:0] sum29; // sfix33_En30
  wire signed [32:0] add_signext_56; // sfix33_En30
  wire signed [32:0] add_signext_57; // sfix33_En30
  wire signed [33:0] add_temp_28; // sfix34_En30
  wire signed [32:0] sum30; // sfix33_En30
  wire signed [32:0] add_signext_58; // sfix33_En30
  wire signed [32:0] add_signext_59; // sfix33_En30
  wire signed [33:0] add_temp_29; // sfix34_En30
  wire signed [32:0] sum31; // sfix33_En30
  wire signed [32:0] add_signext_60; // sfix33_En30
  wire signed [32:0] add_signext_61; // sfix33_En30
  wire signed [33:0] add_temp_30; // sfix34_En30
  wire signed [32:0] sum32; // sfix33_En30
  wire signed [32:0] add_signext_62; // sfix33_En30
  wire signed [32:0] add_signext_63; // sfix33_En30
  wire signed [33:0] add_temp_31; // sfix34_En30
  wire signed [32:0] sum33; // sfix33_En30
  wire signed [32:0] add_signext_64; // sfix33_En30
  wire signed [32:0] add_signext_65; // sfix33_En30
  wire signed [33:0] add_temp_32; // sfix34_En30
  wire signed [32:0] sum34; // sfix33_En30
  wire signed [32:0] add_signext_66; // sfix33_En30
  wire signed [32:0] add_signext_67; // sfix33_En30
  wire signed [33:0] add_temp_33; // sfix34_En30
  wire signed [32:0] sum35; // sfix33_En30
  wire signed [32:0] add_signext_68; // sfix33_En30
  wire signed [32:0] add_signext_69; // sfix33_En30
  wire signed [33:0] add_temp_34; // sfix34_En30
  wire signed [32:0] sum36; // sfix33_En30
  wire signed [32:0] add_signext_70; // sfix33_En30
  wire signed [32:0] add_signext_71; // sfix33_En30
  wire signed [33:0] add_temp_35; // sfix34_En30
  wire signed [32:0] sum37; // sfix33_En30
  wire signed [32:0] add_signext_72; // sfix33_En30
  wire signed [32:0] add_signext_73; // sfix33_En30
  wire signed [33:0] add_temp_36; // sfix34_En30
  wire signed [32:0] sum38; // sfix33_En30
  wire signed [32:0] add_signext_74; // sfix33_En30
  wire signed [32:0] add_signext_75; // sfix33_En30
  wire signed [33:0] add_temp_37; // sfix34_En30
  wire signed [32:0] sum39; // sfix33_En30
  wire signed [32:0] add_signext_76; // sfix33_En30
  wire signed [32:0] add_signext_77; // sfix33_En30
  wire signed [33:0] add_temp_38; // sfix34_En30
  wire signed [32:0] sum40; // sfix33_En30
  wire signed [32:0] add_signext_78; // sfix33_En30
  wire signed [32:0] add_signext_79; // sfix33_En30
  wire signed [33:0] add_temp_39; // sfix34_En30
  wire signed [23:0] output_typeconvert; // sfix24_En23
  reg  signed [23:0] output_register; // sfix24_En23

  // Block Statements
  always @( posedge clk )
    begin: Delay_Pipeline_process
      if (resetn == 1'b0) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[40] * coeff41;
  assign product41 = ((mul_temp[39] == 1'b0 & mul_temp[38] != 1'b0) || (mul_temp[39] == 1'b0 && mul_temp[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp[39] == 1'b1 && mul_temp[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp[38:0] + {mul_temp[8], {7{~mul_temp[8]}}})>>>8;

  assign mul_temp_1 = delay_pipeline[39] * coeff40;
  assign product40 = ((mul_temp_1[39] == 1'b0 & mul_temp_1[38] != 1'b0) || (mul_temp_1[39] == 1'b0 && mul_temp_1[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_1[39] == 1'b1 && mul_temp_1[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_1[38:0] + {mul_temp_1[8], {7{~mul_temp_1[8]}}})>>>8;

  assign mul_temp_2 = delay_pipeline[38] * coeff39;
  assign product39 = ((mul_temp_2[39] == 1'b0 & mul_temp_2[38] != 1'b0) || (mul_temp_2[39] == 1'b0 && mul_temp_2[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_2[39] == 1'b1 && mul_temp_2[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_2[38:0] + {mul_temp_2[8], {7{~mul_temp_2[8]}}})>>>8;

  assign mul_temp_3 = delay_pipeline[37] * coeff38;
  assign product38 = ((mul_temp_3[39] == 1'b0 & mul_temp_3[38] != 1'b0) || (mul_temp_3[39] == 1'b0 && mul_temp_3[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_3[39] == 1'b1 && mul_temp_3[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_3[38:0] + {mul_temp_3[8], {7{~mul_temp_3[8]}}})>>>8;

  assign mul_temp_4 = delay_pipeline[36] * coeff37;
  assign product37 = ((mul_temp_4[39] == 1'b0 & mul_temp_4[38] != 1'b0) || (mul_temp_4[39] == 1'b0 && mul_temp_4[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_4[39] == 1'b1 && mul_temp_4[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_4[38:0] + {mul_temp_4[8], {7{~mul_temp_4[8]}}})>>>8;

  assign mul_temp_5 = delay_pipeline[35] * coeff36;
  assign product36 = ((mul_temp_5[39] == 1'b0 & mul_temp_5[38] != 1'b0) || (mul_temp_5[39] == 1'b0 && mul_temp_5[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_5[39] == 1'b1 && mul_temp_5[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_5[38:0] + {mul_temp_5[8], {7{~mul_temp_5[8]}}})>>>8;

  assign mul_temp_6 = delay_pipeline[34] * coeff35;
  assign product35 = ((mul_temp_6[39] == 1'b0 & mul_temp_6[38] != 1'b0) || (mul_temp_6[39] == 1'b0 && mul_temp_6[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_6[39] == 1'b1 && mul_temp_6[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_6[38:0] + {mul_temp_6[8], {7{~mul_temp_6[8]}}})>>>8;

  assign mul_temp_7 = delay_pipeline[33] * coeff34;
  assign product34 = ((mul_temp_7[39] == 1'b0 & mul_temp_7[38] != 1'b0) || (mul_temp_7[39] == 1'b0 && mul_temp_7[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_7[39] == 1'b1 && mul_temp_7[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_7[38:0] + {mul_temp_7[8], {7{~mul_temp_7[8]}}})>>>8;

  assign mul_temp_8 = delay_pipeline[32] * coeff33;
  assign product33 = ((mul_temp_8[39] == 1'b0 & mul_temp_8[38] != 1'b0) || (mul_temp_8[39] == 1'b0 && mul_temp_8[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_8[39] == 1'b1 && mul_temp_8[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_8[38:0] + {mul_temp_8[8], {7{~mul_temp_8[8]}}})>>>8;

  assign mul_temp_9 = delay_pipeline[31] * coeff32;
  assign product32 = ((mul_temp_9[39] == 1'b0 & mul_temp_9[38] != 1'b0) || (mul_temp_9[39] == 1'b0 && mul_temp_9[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_9[39] == 1'b1 && mul_temp_9[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_9[38:0] + {mul_temp_9[8], {7{~mul_temp_9[8]}}})>>>8;

  assign mul_temp_10 = delay_pipeline[30] * coeff31;
  assign product31 = ((mul_temp_10[39] == 1'b0 & mul_temp_10[38] != 1'b0) || (mul_temp_10[39] == 1'b0 && mul_temp_10[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_10[39] == 1'b1 && mul_temp_10[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_10[38:0] + {mul_temp_10[8], {7{~mul_temp_10[8]}}})>>>8;

  assign mul_temp_11 = delay_pipeline[29] * coeff30;
  assign product30 = ((mul_temp_11[39] == 1'b0 & mul_temp_11[38] != 1'b0) || (mul_temp_11[39] == 1'b0 && mul_temp_11[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_11[39] == 1'b1 && mul_temp_11[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_11[38:0] + {mul_temp_11[8], {7{~mul_temp_11[8]}}})>>>8;

  assign mul_temp_12 = delay_pipeline[28] * coeff29;
  assign product29 = ((mul_temp_12[39] == 1'b0 & mul_temp_12[38] != 1'b0) || (mul_temp_12[39] == 1'b0 && mul_temp_12[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_12[39] == 1'b1 && mul_temp_12[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_12[38:0] + {mul_temp_12[8], {7{~mul_temp_12[8]}}})>>>8;

  assign mul_temp_13 = delay_pipeline[27] * coeff28;
  assign product28 = ((mul_temp_13[39] == 1'b0 & mul_temp_13[38] != 1'b0) || (mul_temp_13[39] == 1'b0 && mul_temp_13[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_13[39] == 1'b1 && mul_temp_13[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_13[38:0] + {mul_temp_13[8], {7{~mul_temp_13[8]}}})>>>8;

  assign mul_temp_14 = delay_pipeline[26] * coeff27;
  assign product27 = ((mul_temp_14[39] == 1'b0 & mul_temp_14[38] != 1'b0) || (mul_temp_14[39] == 1'b0 && mul_temp_14[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_14[39] == 1'b1 && mul_temp_14[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_14[38:0] + {mul_temp_14[8], {7{~mul_temp_14[8]}}})>>>8;

  assign mul_temp_15 = delay_pipeline[25] * coeff26;
  assign product26 = ((mul_temp_15[39] == 1'b0 & mul_temp_15[38] != 1'b0) || (mul_temp_15[39] == 1'b0 && mul_temp_15[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_15[39] == 1'b1 && mul_temp_15[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_15[38:0] + {mul_temp_15[8], {7{~mul_temp_15[8]}}})>>>8;

  assign mul_temp_16 = delay_pipeline[24] * coeff25;
  assign product25 = ((mul_temp_16[39] == 1'b0 & mul_temp_16[38] != 1'b0) || (mul_temp_16[39] == 1'b0 && mul_temp_16[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_16[39] == 1'b1 && mul_temp_16[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_16[38:0] + {mul_temp_16[8], {7{~mul_temp_16[8]}}})>>>8;

  assign mul_temp_17 = delay_pipeline[23] * coeff24;
  assign product24 = ((mul_temp_17[39] == 1'b0 & mul_temp_17[38] != 1'b0) || (mul_temp_17[39] == 1'b0 && mul_temp_17[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_17[39] == 1'b1 && mul_temp_17[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_17[38:0] + {mul_temp_17[8], {7{~mul_temp_17[8]}}})>>>8;

  assign mul_temp_18 = delay_pipeline[22] * coeff23;
  assign product23 = ((mul_temp_18[39] == 1'b0 & mul_temp_18[38] != 1'b0) || (mul_temp_18[39] == 1'b0 && mul_temp_18[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_18[39] == 1'b1 && mul_temp_18[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_18[38:0] + {mul_temp_18[8], {7{~mul_temp_18[8]}}})>>>8;

  assign mul_temp_19 = delay_pipeline[21] * coeff22;
  assign product22 = ((mul_temp_19[39] == 1'b0 & mul_temp_19[38] != 1'b0) || (mul_temp_19[39] == 1'b0 && mul_temp_19[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_19[39] == 1'b1 && mul_temp_19[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_19[38:0] + {mul_temp_19[8], {7{~mul_temp_19[8]}}})>>>8;

  assign mul_temp_20 = delay_pipeline[20] * coeff21;
  assign product21 = ((mul_temp_20[39] == 1'b0 & mul_temp_20[38] != 1'b0) || (mul_temp_20[39] == 1'b0 && mul_temp_20[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_20[39] == 1'b1 && mul_temp_20[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_20[38:0] + {mul_temp_20[8], {7{~mul_temp_20[8]}}})>>>8;

  assign mul_temp_21 = delay_pipeline[19] * coeff20;
  assign product20 = ((mul_temp_21[39] == 1'b0 & mul_temp_21[38] != 1'b0) || (mul_temp_21[39] == 1'b0 && mul_temp_21[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_21[39] == 1'b1 && mul_temp_21[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_21[38:0] + {mul_temp_21[8], {7{~mul_temp_21[8]}}})>>>8;

  assign mul_temp_22 = delay_pipeline[18] * coeff19;
  assign product19 = ((mul_temp_22[39] == 1'b0 & mul_temp_22[38] != 1'b0) || (mul_temp_22[39] == 1'b0 && mul_temp_22[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_22[39] == 1'b1 && mul_temp_22[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_22[38:0] + {mul_temp_22[8], {7{~mul_temp_22[8]}}})>>>8;

  assign mul_temp_23 = delay_pipeline[17] * coeff18;
  assign product18 = ((mul_temp_23[39] == 1'b0 & mul_temp_23[38] != 1'b0) || (mul_temp_23[39] == 1'b0 && mul_temp_23[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_23[39] == 1'b1 && mul_temp_23[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_23[38:0] + {mul_temp_23[8], {7{~mul_temp_23[8]}}})>>>8;

  assign mul_temp_24 = delay_pipeline[16] * coeff17;
  assign product17 = ((mul_temp_24[39] == 1'b0 & mul_temp_24[38] != 1'b0) || (mul_temp_24[39] == 1'b0 && mul_temp_24[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_24[39] == 1'b1 && mul_temp_24[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_24[38:0] + {mul_temp_24[8], {7{~mul_temp_24[8]}}})>>>8;

  assign mul_temp_25 = delay_pipeline[15] * coeff16;
  assign product16 = ((mul_temp_25[39] == 1'b0 & mul_temp_25[38] != 1'b0) || (mul_temp_25[39] == 1'b0 && mul_temp_25[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_25[39] == 1'b1 && mul_temp_25[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_25[38:0] + {mul_temp_25[8], {7{~mul_temp_25[8]}}})>>>8;

  assign mul_temp_26 = delay_pipeline[14] * coeff15;
  assign product15 = ((mul_temp_26[39] == 1'b0 & mul_temp_26[38] != 1'b0) || (mul_temp_26[39] == 1'b0 && mul_temp_26[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_26[39] == 1'b1 && mul_temp_26[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_26[38:0] + {mul_temp_26[8], {7{~mul_temp_26[8]}}})>>>8;

  assign mul_temp_27 = delay_pipeline[13] * coeff14;
  assign product14 = ((mul_temp_27[39] == 1'b0 & mul_temp_27[38] != 1'b0) || (mul_temp_27[39] == 1'b0 && mul_temp_27[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_27[39] == 1'b1 && mul_temp_27[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_27[38:0] + {mul_temp_27[8], {7{~mul_temp_27[8]}}})>>>8;

  assign mul_temp_28 = delay_pipeline[12] * coeff13;
  assign product13 = ((mul_temp_28[39] == 1'b0 & mul_temp_28[38] != 1'b0) || (mul_temp_28[39] == 1'b0 && mul_temp_28[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_28[39] == 1'b1 && mul_temp_28[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_28[38:0] + {mul_temp_28[8], {7{~mul_temp_28[8]}}})>>>8;

  assign mul_temp_29 = delay_pipeline[11] * coeff12;
  assign product12 = ((mul_temp_29[39] == 1'b0 & mul_temp_29[38] != 1'b0) || (mul_temp_29[39] == 1'b0 && mul_temp_29[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_29[39] == 1'b1 && mul_temp_29[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_29[38:0] + {mul_temp_29[8], {7{~mul_temp_29[8]}}})>>>8;

  assign mul_temp_30 = delay_pipeline[10] * coeff11;
  assign product11 = ((mul_temp_30[39] == 1'b0 & mul_temp_30[38] != 1'b0) || (mul_temp_30[39] == 1'b0 && mul_temp_30[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_30[39] == 1'b1 && mul_temp_30[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_30[38:0] + {mul_temp_30[8], {7{~mul_temp_30[8]}}})>>>8;

  assign mul_temp_31 = delay_pipeline[9] * coeff10;
  assign product10 = ((mul_temp_31[39] == 1'b0 & mul_temp_31[38] != 1'b0) || (mul_temp_31[39] == 1'b0 && mul_temp_31[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_31[39] == 1'b1 && mul_temp_31[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_31[38:0] + {mul_temp_31[8], {7{~mul_temp_31[8]}}})>>>8;

  assign mul_temp_32 = delay_pipeline[8] * coeff9;
  assign product9 = ((mul_temp_32[39] == 1'b0 & mul_temp_32[38] != 1'b0) || (mul_temp_32[39] == 1'b0 && mul_temp_32[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_32[39] == 1'b1 && mul_temp_32[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_32[38:0] + {mul_temp_32[8], {7{~mul_temp_32[8]}}})>>>8;

  assign mul_temp_33 = delay_pipeline[7] * coeff8;
  assign product8 = ((mul_temp_33[39] == 1'b0 & mul_temp_33[38] != 1'b0) || (mul_temp_33[39] == 1'b0 && mul_temp_33[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_33[39] == 1'b1 && mul_temp_33[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_33[38:0] + {mul_temp_33[8], {7{~mul_temp_33[8]}}})>>>8;

  assign mul_temp_34 = delay_pipeline[6] * coeff7;
  assign product7 = ((mul_temp_34[39] == 1'b0 & mul_temp_34[38] != 1'b0) || (mul_temp_34[39] == 1'b0 && mul_temp_34[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_34[39] == 1'b1 && mul_temp_34[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_34[38:0] + {mul_temp_34[8], {7{~mul_temp_34[8]}}})>>>8;

  assign mul_temp_35 = delay_pipeline[5] * coeff6;
  assign product6 = ((mul_temp_35[39] == 1'b0 & mul_temp_35[38] != 1'b0) || (mul_temp_35[39] == 1'b0 && mul_temp_35[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_35[39] == 1'b1 && mul_temp_35[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_35[38:0] + {mul_temp_35[8], {7{~mul_temp_35[8]}}})>>>8;

  assign mul_temp_36 = delay_pipeline[4] * coeff5;
  assign product5 = ((mul_temp_36[39] == 1'b0 & mul_temp_36[38] != 1'b0) || (mul_temp_36[39] == 1'b0 && mul_temp_36[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_36[39] == 1'b1 && mul_temp_36[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_36[38:0] + {mul_temp_36[8], {7{~mul_temp_36[8]}}})>>>8;

  assign mul_temp_37 = delay_pipeline[3] * coeff4;
  assign product4 = ((mul_temp_37[39] == 1'b0 & mul_temp_37[38] != 1'b0) || (mul_temp_37[39] == 1'b0 && mul_temp_37[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_37[39] == 1'b1 && mul_temp_37[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_37[38:0] + {mul_temp_37[8], {7{~mul_temp_37[8]}}})>>>8;

  assign mul_temp_38 = delay_pipeline[2] * coeff3;
  assign product3 = ((mul_temp_38[39] == 1'b0 & mul_temp_38[38] != 1'b0) || (mul_temp_38[39] == 1'b0 && mul_temp_38[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_38[39] == 1'b1 && mul_temp_38[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_38[38:0] + {mul_temp_38[8], {7{~mul_temp_38[8]}}})>>>8;

  assign mul_temp_39 = delay_pipeline[1] * coeff2;
  assign product2 = ((mul_temp_39[39] == 1'b0 & mul_temp_39[38] != 1'b0) || (mul_temp_39[39] == 1'b0 && mul_temp_39[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_39[39] == 1'b1 && mul_temp_39[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_39[38:0] + {mul_temp_39[8], {7{~mul_temp_39[8]}}})>>>8;

  assign product1_cast = $signed({{2{product1[30]}}, product1});

  assign mul_temp_40 = delay_pipeline[0] * coeff1;
  assign product1 = ((mul_temp_40[39] == 1'b0 & mul_temp_40[38] != 1'b0) || (mul_temp_40[39] == 1'b0 && mul_temp_40[38:8] == 31'b0111111111111111111111111111111) // special case0
) ? 31'b0111111111111111111111111111111 : 
      (mul_temp_40[39] == 1'b1 && mul_temp_40[38] != 1'b1) ? 31'b1000000000000000000000000000000 : (mul_temp_40[38:0] + {mul_temp_40[8], {7{~mul_temp_40[8]}}})>>>8;

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{2{product2[30]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = ((add_temp[33] == 1'b0 & add_temp[32] != 1'b0) || (add_temp[33] == 1'b0 && add_temp[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp[33] == 1'b1 && add_temp[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp[32:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{2{product3[30]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = ((add_temp_1[33] == 1'b0 & add_temp_1[32] != 1'b0) || (add_temp_1[33] == 1'b0 && add_temp_1[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_1[33] == 1'b1 && add_temp_1[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_1[32:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{2{product4[30]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = ((add_temp_2[33] == 1'b0 & add_temp_2[32] != 1'b0) || (add_temp_2[33] == 1'b0 && add_temp_2[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_2[33] == 1'b1 && add_temp_2[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_2[32:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{2{product5[30]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = ((add_temp_3[33] == 1'b0 & add_temp_3[32] != 1'b0) || (add_temp_3[33] == 1'b0 && add_temp_3[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_3[33] == 1'b1 && add_temp_3[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_3[32:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{2{product6[30]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = ((add_temp_4[33] == 1'b0 & add_temp_4[32] != 1'b0) || (add_temp_4[33] == 1'b0 && add_temp_4[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_4[33] == 1'b1 && add_temp_4[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_4[32:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{2{product7[30]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = ((add_temp_5[33] == 1'b0 & add_temp_5[32] != 1'b0) || (add_temp_5[33] == 1'b0 && add_temp_5[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_5[33] == 1'b1 && add_temp_5[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_5[32:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{2{product8[30]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = ((add_temp_6[33] == 1'b0 & add_temp_6[32] != 1'b0) || (add_temp_6[33] == 1'b0 && add_temp_6[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_6[33] == 1'b1 && add_temp_6[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_6[32:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{2{product9[30]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = ((add_temp_7[33] == 1'b0 & add_temp_7[32] != 1'b0) || (add_temp_7[33] == 1'b0 && add_temp_7[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_7[33] == 1'b1 && add_temp_7[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_7[32:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{2{product10[30]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = ((add_temp_8[33] == 1'b0 & add_temp_8[32] != 1'b0) || (add_temp_8[33] == 1'b0 && add_temp_8[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_8[33] == 1'b1 && add_temp_8[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_8[32:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{2{product11[30]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = ((add_temp_9[33] == 1'b0 & add_temp_9[32] != 1'b0) || (add_temp_9[33] == 1'b0 && add_temp_9[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_9[33] == 1'b1 && add_temp_9[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_9[32:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{2{product12[30]}}, product12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = ((add_temp_10[33] == 1'b0 & add_temp_10[32] != 1'b0) || (add_temp_10[33] == 1'b0 && add_temp_10[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_10[33] == 1'b1 && add_temp_10[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_10[32:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{2{product13[30]}}, product13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = ((add_temp_11[33] == 1'b0 & add_temp_11[32] != 1'b0) || (add_temp_11[33] == 1'b0 && add_temp_11[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_11[33] == 1'b1 && add_temp_11[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_11[32:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{2{product14[30]}}, product14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = ((add_temp_12[33] == 1'b0 & add_temp_12[32] != 1'b0) || (add_temp_12[33] == 1'b0 && add_temp_12[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_12[33] == 1'b1 && add_temp_12[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_12[32:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{2{product15[30]}}, product15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = ((add_temp_13[33] == 1'b0 & add_temp_13[32] != 1'b0) || (add_temp_13[33] == 1'b0 && add_temp_13[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_13[33] == 1'b1 && add_temp_13[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_13[32:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{2{product16[30]}}, product16});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = ((add_temp_14[33] == 1'b0 & add_temp_14[32] != 1'b0) || (add_temp_14[33] == 1'b0 && add_temp_14[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_14[33] == 1'b1 && add_temp_14[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_14[32:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{2{product17[30]}}, product17});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = ((add_temp_15[33] == 1'b0 & add_temp_15[32] != 1'b0) || (add_temp_15[33] == 1'b0 && add_temp_15[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_15[33] == 1'b1 && add_temp_15[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_15[32:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{2{product18[30]}}, product18});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = ((add_temp_16[33] == 1'b0 & add_temp_16[32] != 1'b0) || (add_temp_16[33] == 1'b0 && add_temp_16[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_16[33] == 1'b1 && add_temp_16[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_16[32:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{2{product19[30]}}, product19});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = ((add_temp_17[33] == 1'b0 & add_temp_17[32] != 1'b0) || (add_temp_17[33] == 1'b0 && add_temp_17[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_17[33] == 1'b1 && add_temp_17[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_17[32:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{2{product20[30]}}, product20});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = ((add_temp_18[33] == 1'b0 & add_temp_18[32] != 1'b0) || (add_temp_18[33] == 1'b0 && add_temp_18[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_18[33] == 1'b1 && add_temp_18[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_18[32:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{2{product21[30]}}, product21});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = ((add_temp_19[33] == 1'b0 & add_temp_19[32] != 1'b0) || (add_temp_19[33] == 1'b0 && add_temp_19[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_19[33] == 1'b1 && add_temp_19[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_19[32:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{2{product22[30]}}, product22});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = ((add_temp_20[33] == 1'b0 & add_temp_20[32] != 1'b0) || (add_temp_20[33] == 1'b0 && add_temp_20[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_20[33] == 1'b1 && add_temp_20[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_20[32:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{2{product23[30]}}, product23});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = ((add_temp_21[33] == 1'b0 & add_temp_21[32] != 1'b0) || (add_temp_21[33] == 1'b0 && add_temp_21[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_21[33] == 1'b1 && add_temp_21[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_21[32:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{2{product24[30]}}, product24});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = ((add_temp_22[33] == 1'b0 & add_temp_22[32] != 1'b0) || (add_temp_22[33] == 1'b0 && add_temp_22[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_22[33] == 1'b1 && add_temp_22[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_22[32:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{2{product25[30]}}, product25});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = ((add_temp_23[33] == 1'b0 & add_temp_23[32] != 1'b0) || (add_temp_23[33] == 1'b0 && add_temp_23[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_23[33] == 1'b1 && add_temp_23[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_23[32:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{2{product26[30]}}, product26});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = ((add_temp_24[33] == 1'b0 & add_temp_24[32] != 1'b0) || (add_temp_24[33] == 1'b0 && add_temp_24[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_24[33] == 1'b1 && add_temp_24[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_24[32:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{2{product27[30]}}, product27});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = ((add_temp_25[33] == 1'b0 & add_temp_25[32] != 1'b0) || (add_temp_25[33] == 1'b0 && add_temp_25[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_25[33] == 1'b1 && add_temp_25[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_25[32:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{2{product28[30]}}, product28});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = ((add_temp_26[33] == 1'b0 & add_temp_26[32] != 1'b0) || (add_temp_26[33] == 1'b0 && add_temp_26[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_26[33] == 1'b1 && add_temp_26[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_26[32:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{2{product29[30]}}, product29});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = ((add_temp_27[33] == 1'b0 & add_temp_27[32] != 1'b0) || (add_temp_27[33] == 1'b0 && add_temp_27[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_27[33] == 1'b1 && add_temp_27[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_27[32:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{2{product30[30]}}, product30});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = ((add_temp_28[33] == 1'b0 & add_temp_28[32] != 1'b0) || (add_temp_28[33] == 1'b0 && add_temp_28[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_28[33] == 1'b1 && add_temp_28[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_28[32:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{2{product31[30]}}, product31});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = ((add_temp_29[33] == 1'b0 & add_temp_29[32] != 1'b0) || (add_temp_29[33] == 1'b0 && add_temp_29[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_29[33] == 1'b1 && add_temp_29[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_29[32:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = $signed({{2{product32[30]}}, product32});
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = ((add_temp_30[33] == 1'b0 & add_temp_30[32] != 1'b0) || (add_temp_30[33] == 1'b0 && add_temp_30[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_30[33] == 1'b1 && add_temp_30[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_30[32:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = $signed({{2{product33[30]}}, product33});
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = ((add_temp_31[33] == 1'b0 & add_temp_31[32] != 1'b0) || (add_temp_31[33] == 1'b0 && add_temp_31[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_31[33] == 1'b1 && add_temp_31[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_31[32:0];

  assign add_signext_64 = sum32;
  assign add_signext_65 = $signed({{2{product34[30]}}, product34});
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum33 = ((add_temp_32[33] == 1'b0 & add_temp_32[32] != 1'b0) || (add_temp_32[33] == 1'b0 && add_temp_32[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_32[33] == 1'b1 && add_temp_32[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_32[32:0];

  assign add_signext_66 = sum33;
  assign add_signext_67 = $signed({{2{product35[30]}}, product35});
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum34 = ((add_temp_33[33] == 1'b0 & add_temp_33[32] != 1'b0) || (add_temp_33[33] == 1'b0 && add_temp_33[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_33[33] == 1'b1 && add_temp_33[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_33[32:0];

  assign add_signext_68 = sum34;
  assign add_signext_69 = $signed({{2{product36[30]}}, product36});
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum35 = ((add_temp_34[33] == 1'b0 & add_temp_34[32] != 1'b0) || (add_temp_34[33] == 1'b0 && add_temp_34[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_34[33] == 1'b1 && add_temp_34[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_34[32:0];

  assign add_signext_70 = sum35;
  assign add_signext_71 = $signed({{2{product37[30]}}, product37});
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum36 = ((add_temp_35[33] == 1'b0 & add_temp_35[32] != 1'b0) || (add_temp_35[33] == 1'b0 && add_temp_35[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_35[33] == 1'b1 && add_temp_35[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_35[32:0];

  assign add_signext_72 = sum36;
  assign add_signext_73 = $signed({{2{product38[30]}}, product38});
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum37 = ((add_temp_36[33] == 1'b0 & add_temp_36[32] != 1'b0) || (add_temp_36[33] == 1'b0 && add_temp_36[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_36[33] == 1'b1 && add_temp_36[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_36[32:0];

  assign add_signext_74 = sum37;
  assign add_signext_75 = $signed({{2{product39[30]}}, product39});
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum38 = ((add_temp_37[33] == 1'b0 & add_temp_37[32] != 1'b0) || (add_temp_37[33] == 1'b0 && add_temp_37[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_37[33] == 1'b1 && add_temp_37[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_37[32:0];

  assign add_signext_76 = sum38;
  assign add_signext_77 = $signed({{2{product40[30]}}, product40});
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum39 = ((add_temp_38[33] == 1'b0 & add_temp_38[32] != 1'b0) || (add_temp_38[33] == 1'b0 && add_temp_38[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_38[33] == 1'b1 && add_temp_38[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_38[32:0];

  assign add_signext_78 = sum39;
  assign add_signext_79 = $signed({{2{product41[30]}}, product41});
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum40 = ((add_temp_39[33] == 1'b0 & add_temp_39[32] != 1'b0) || (add_temp_39[33] == 1'b0 && add_temp_39[32:0] == 33'b011111111111111111111111111111111) // special case0
) ? 33'b011111111111111111111111111111111 : 
      (add_temp_39[33] == 1'b1 && add_temp_39[32] != 1'b1) ? 33'b100000000000000000000000000000000 : add_temp_39[32:0];

  assign output_typeconvert = ((sum40[32] == 1'b0 & sum40[31:30] != 2'b00) || (sum40[32] == 1'b0 && sum40[30:7] == 24'b011111111111111111111111) // special case0
) ? 24'b011111111111111111111111 : 
      (sum40[32] == 1'b1 && sum40[31:30] != 2'b11) ? 24'b100000000000000000000000 : (sum40[30:0] + {sum40[7], {6{~sum40[7]}}})>>>7;

  always @ (posedge clk )
    begin: Output_Register_process
      if (resetn == 1'b0) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filterBP13
